export const ENTITLEMENT_SERVICE = Symbol("ENTITLEMENT_SERVICE");
export const BILLING_RECONCILER = Symbol("BILLING_RECONCILER");
export const BILLING_STATE_STORE = Symbol("BILLING_STATE_STORE");
export const STRIPE_BILLING_PORT = Symbol("STRIPE_BILLING_PORT");
