/**
 * Bake WINGMAN_API_URL into config.js for static Vercel deploys.
 * Local/dev: empty apiUrl → api.js falls back to localhost:3000.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const apiUrl = String(process.env.WINGMAN_API_URL || "")
  .trim()
  .replace(/\/$/, "");

const livingMap = process.env.WINGMAN_LIVING_MAP_V1 === "true";

const body = `/* generated by scripts/write-config.mjs — do not edit by hand on Vercel */\nwindow.__WINGMAN_CONFIG__ = ${JSON.stringify({ apiUrl, livingMap })};\n`;
writeFileSync(join(root, "config.js"), body, "utf8");
console.log(`[wingman] config.js apiUrl=${apiUrl || "(empty — local fallback)"} livingMap=${livingMap}`);
