/**
 * Bake WINGMAN_API_URL into config.js for static Vercel deploys.
 * Local/dev: empty apiUrl → api.js falls back to localhost:3000.
 * On Vercel, stamp asset version onto local JS/CSS and sw.js so PWAs drop stale shells.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const apiUrl = String(process.env.WINGMAN_API_URL || "")
  .trim()
  .replace(/\/$/, "");

const livingMap = process.env.WINGMAN_LIVING_MAP_V1 !== "false";
const assetV = String(process.env.VERCEL_GIT_COMMIT_SHA || process.env.WINGMAN_ASSET_V || "dev")
  .replace(/[^a-zA-Z0-9._-]/g, "")
  .slice(0, 40) || "dev";

const body = `/* generated by scripts/write-config.mjs — do not edit by hand on Vercel */\nwindow.__WINGMAN_CONFIG__ = ${JSON.stringify({ apiUrl, livingMap, assetV })};\n`;
writeFileSync(join(root, "config.js"), body, "utf8");
console.log(`[wingman] config.js apiUrl=${apiUrl || "(empty — local fallback)"} livingMap=${livingMap} assetV=${assetV}`);

function stampServiceWorker(sha) {
  const swPath = join(root, "sw.js");
  const sw = readFileSync(swPath, "utf8").replace(
    /var ASSET_V = '[^']*';/,
    "var ASSET_V = '" + sha + "';",
  );
  writeFileSync(swPath, sw, "utf8");
}

function bustHtmlAssets(sha) {
  const indexPath = join(root, "index.html");
  const html = readFileSync(indexPath, "utf8").replace(
    /(src|href)="(\/?[^"]+\.(?:js|css))(?:\?v=[^"]*)?"/g,
    function (m, attr, file) {
      if (/^https?:\/\//i.test(file)) return m;
      return attr + '="' + file + "?v=" + sha + '"';
    },
  );
  writeFileSync(indexPath, html, "utf8");
}

if (process.env.VERCEL || process.env.WINGMAN_ASSET_V) {
  stampServiceWorker(assetV);
  bustHtmlAssets(assetV);
  console.log("[wingman] stamped PWA assets assetV=" + assetV);
}
